### ISSUE TITLE
Add a "Module" constructor from "Package"

### ISSUE THREAD

**Issue by DorianBourgeoisat** [rowlul/modthara#9]
To add mods to the modsettings/mod order, a "Module" object stands to be created, and inserted or appended using the ModSettings methods. With mods already loaded in the mod order, no need to create them as they are generated while loading the modsettings, but for mods that weren't there to begin with, the object needs to be created from the package itself. Some mods come with a json metadata file, but not all of them as BG3MM uses the meta.lsx contained inside the package file.

I think the most reasonable way to do things would be to have a constructor taking a package and reading the attributes from the meta.lsx file (example : https://bg3.wiki/wiki/Modding:Creating_meta.lsx), the attributes are the same ones as the modsettings.lsx anyway.

I am available to implement this if I have your greenlight.

**Comment by rolowilde** [comment]
Can you provide a code example? I'm fairly sure what you've described is already implemented in `ModsService`, but maybe your approach is more efficient.

**Comment by DorianBourgeoisat** [comment]
My bad, didn't see ModMetadata inherited from Module, and that the ModPackageManager instanciated those from a package.

**Comment by rolowilde** [comment]
Yep, you can look through the UI code to see it in action. `Modthara.Manager` is just a higher abstraction of `Modthara.Lari`, which is based on the existing LSLib.
